# Generated by Django 3.2.11 on 2022-01-19 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='タイトル', max_length=100)),
                ('staff', models.TextField(help_text='スタッフから')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_target', models.CharField(help_text='長期目標', max_length=100)),
                ('long_target_summary', models.TextField(help_text='長期目標の詳細について')),
                ('long_target_date', models.DateField(default=datetime.datetime.now, help_text='長期目標の期日')),
                ('long_target_link', models.TextField(blank=True, help_text='YouTube の埋め込みリンク', null=True)),
                ('long_target_link_start', models.IntegerField(blank=True, default=0, help_text='YouTube の再生開始時間', null=True)),
                ('middle_target', models.CharField(help_text='中期目標', max_length=100)),
                ('middle_target_summary', models.TextField(help_text='中期目標の詳細について')),
                ('middle_target_link', models.TextField(blank=True, help_text='YouTube の埋め込みリンク', null=True)),
                ('middle_target_link_start', models.IntegerField(blank=True, default=0, help_text='YouTube の再生開始時間', null=True)),
                ('short_target', models.CharField(help_text='短期目標', max_length=100)),
                ('short_target_summary', models.TextField(help_text='短期目標の詳細について')),
                ('short_target_link', models.TextField(blank=True, help_text='YouTube の埋め込みリンク', null=True)),
                ('short_target_link_start', models.IntegerField(blank=True, default=0, help_text='YouTube の再生開始時間', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dairy_target', models.CharField(help_text='今日のタイトル', max_length=100)),
                ('dairy_target_menu', models.TextField(help_text='トレーニングメニュー')),
                ('dairy_target_summary', models.TextField(help_text='意識したこと・達成したこと')),
                ('training_time', models.DecimalField(decimal_places=1, default=0, help_text='運動の合計時間(hour)', max_digits=4)),
                ('stability_time', models.IntegerField(default=0, help_text='体幹トレーニングの合計時間(min)')),
                ('stretch_time', models.IntegerField(default=0, help_text='ストレッチの合計時間(min)')),
                ('body_temperature', models.DecimalField(decimal_places=1, default=0, help_text='体温', max_digits=4)),
                ('body_weight', models.DecimalField(decimal_places=1, default=0, help_text='体重', max_digits=4)),
                ('sleeping_hours', models.DecimalField(decimal_places=1, default=0, help_text='睡眠時間(hour)', max_digits=4)),
                ('date', models.DateField(default=datetime.datetime.now, help_text='日付')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='今週のタイトル', max_length=100)),
                ('summary', models.TextField(help_text='今週の振り返り')),
            ],
        ),
    ]
