# Generated by Django 3.2.11 on 2022-01-17 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staff_target_training_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='long_target_link',
            field=models.CharField(blank=True, help_text='YouTube の埋め込みリンク', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='middle_target_link',
            field=models.CharField(blank=True, help_text='YouTube の埋め込みリンク', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='short_target_link',
            field=models.CharField(blank=True, help_text='YouTube の埋め込みリンク', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.datetime.now, help_text='日付'),
        ),
    ]
