# Generated by Django 3.2.11 on 2022-01-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220117_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='long_target_link',
            field=models.TextField(blank=True, help_text='YouTube の埋め込みリンク', null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='middle_target_link',
            field=models.TextField(blank=True, help_text='YouTube の埋め込みリンク', null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='short_target_link',
            field=models.TextField(blank=True, help_text='YouTube の埋め込みリンク', null=True),
        ),
    ]
