# Generated by Django 3.2.11 on 2022-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220117_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='long_target_link_start',
            field=models.IntegerField(blank=True, default=0, help_text='YouTube の再生開始時間', null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='middle_target_link_start',
            field=models.IntegerField(blank=True, default=0, help_text='YouTube の再生開始時間', null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='short_target_link_start',
            field=models.IntegerField(blank=True, default=0, help_text='YouTube の再生開始時間', null=True),
        ),
    ]
