# Generated by Django 3.2.11 on 2022-01-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220117_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='sleeping_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='睡眠時間(hour)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='training',
            name='stability_time',
            field=models.IntegerField(default=0, help_text='体幹トレーニングの合計時間(min)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='stretch_time',
            field=models.IntegerField(default=0, help_text='ストレッチの合計時間(min)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_time',
            field=models.DecimalField(decimal_places=1, default=0, help_text='運動の合計時間(hour)', max_digits=4),
        ),
    ]
